#spring.resources.add-mappings=false
#spring.mvc.throw-exception-if-no-handler-found=true
#spring.http.encoding.force=true
#input.file = C:\\zerofiltre\\services_tech\\100stackoverflow\\100stackoverflow\\sheets.csv
#management.endpoints.web.exposure.include=*
aws-secretmanager:
  secretName: "test-mvp"
  region: "us-west-2"